electionapp/admin/views.py
from electionapp import db
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user
from electionapp.admin.models import User
from electionapp.voting.models import Vote, Party
from electionapp.admin.forms import LoginForm, RegistrationForm

admin_blueprint = Blueprint('admin', __name__, template_folder='templates')

@admin_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('U bent nu uitgelogd')
    return redirect(url_for('index'))

@admin_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash(f'U bent succesvol ingelogd. Uw ID is: {current_user.get_id()}')
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('admin.votes')
                return redirect(next)
    return render_template('login.html', form=form)

@admin_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        # Add to db
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        flash('Bedankt voor de registratie. Er kan nu ingelogd worden!')
        return redirect(url_for('admin.login'))
    return render_template('register.html', form=form)

@admin_blueprint.route('/votes')
@login_required
def votes():
    all_votes = {}
    parties = Party.query.order_by(Party.name).all()
    for party in parties:
        all_votes[party.name] = Vote.query.filter_by(party_id = party.id).all()
    return render_template('votes.html', votes=all_votes)

electionapp/voting/views.py
from electionapp import db
from flask import Blueprint, render_template, redirect, request, url_for, flash
from electionapp.voting.models import Vote, Party, Voter
from electionapp.voting.forms import VotingForm

voting_blueprint = Blueprint('voting', __name__, template_folder='templates')

@voting_blueprint.route('/form')
def form():
    form = VotingForm()
    form.party.choices = [(p.id, p.name) for p in Party.query.order_by('name')]

    return render_template('vote.html', form=form)

@voting_blueprint.route('/vote', methods=['post'])
def vote():
    form = VotingForm()
    form.party.choices = [(p.id, p.name) for p in Party.query.order_by('name')]
    if form.validate_on_submit():
        # Add to db
        voter = Voter(form.name.data)
        db.session.add(voter)
        db.session.commit()
        voter_id = voter.id
        party_id = form.party.data
        vote = Vote(voter_id, party_id)
        db.session.add(vote)
        db.session.commit()

        flash(f"Bedankt {form.name.data}, voor uw stem!")
        return redirect(url_for("voting.thanks"))
    else:
        flash("Ongeldige stem")
        return redirect(url_for("voting.fail"))

@voting_blueprint.route('/thanks')
def thanks():
    return render_template("thanks.html")

@voting_blueprint.route('/fail')
def fail():
    return render_template("fail.html")

electionapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('index') }}">Home</a>
            </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.votes') }}">Overzicht</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.logout') }}">Uitloggen</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.login') }}">Inloggen</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.register') }}">Registreren</a></li>
            {% endif %}
        </ul>
    </nav>

    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <div class="container">
        {% block contents %}
        {% endblock %}
    </div>
</body>
</html>

electionapp/templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block contents %}

<h1>Welkom bij de Waterschapsverkiezingen!</h1>
<a class="btn btn-primary" href="{{ url_for('voting.form') }}">Stem</a>
<a class="btn btn-primary" href="{{ url_for('admin.login') }}">Log in</a>

{% endblock %}