electionapp/voting/models.py
from electionapp import db

class Voter(db.Model):
    __tablename__ = 'voters'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)

    def __init__(self, name):
        self.name = name

class Party(db.Model):
    __tablename__ = 'parties'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)

    def __init__(self, name):
        self.name = name

class Vote(db.Model):
    __tablename__ = 'votes'
    id = db.Column(db.Integer, primary_key=True)

    voter_id = db.Column(db.Integer, db.ForeignKey('voters.id'))
    voter = db.relationship('Voter', backref='Vote', uselist=False)

    party_id = db.Column(db.Integer, db.ForeignKey('parties.id'))
    party = db.relationship('Party', backref='Vote', uselist=False)

    def __init__(self, voter_id, party_id):
        self.voter_id = voter_id
        self.party_id = party_id

    def __repr__(self):
        return f"Stemmer {self.voter.name} heeft gestemd op {self.party.name}"

electionapp/voting/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import InputRequired

class VotingForm(FlaskForm):
    name = StringField("Wat is uw naam?", validators=[InputRequired()])
    party = SelectField("Op welke partij wilt u stemmen?", choices=[])
    submit = SubmitField("Breng uw stem uit")

electionapp/voting/views.py
from electionapp import db
from flask import Blueprint, render_template, redirect, request, url_for, flash
from electionapp.voting.models import Vote, Party, Voter
from electionapp.voting.forms import VotingForm

voting_blueprint = Blueprint('voting', __name__, template_folder='templates')

@voting_blueprint.route('/form')
def form():
    form = VotingForm()
    form.party.choices = [(p.id, p.name) for p in Party.query.order_by('name')]

    return render_template('vote.html', form=form)

@voting_blueprint.route('/vote', methods=['post'])
def vote():
    form = VotingForm()
    form.party.choices = [(p.id, p.name) for p in Party.query.order_by('name')]
    if form.validate_on_submit():
        # Add to db
        voter = Voter(form.name.data)
        db.session.add(voter)
        db.session.commit()
        voter_id = voter.id
        party_id = form.party.data
        vote = Vote(voter_id, party_id)
        db.session.add(vote)
        db.session.commit()

        flash(f"Bedankt {form.name.data}, voor uw stem!")
        return redirect(url_for("voting.thanks"))
    else:
        flash("Ongeldige stem")
        return redirect(url_for("voting.fail"))

@voting_blueprint.route('/thanks')
def thanks():
    return render_template("thanks.html")

@voting_blueprint.route('/fail')
def fail():
    return render_template("fail.html")

electionapp/voting/templates/fail.html
{% extends "base.html" %}

{% block title %}
Mislukt
{% endblock %}

{% block contents %}
<p><a class="btn btn-primary" href="{{ url_for('index') }}">Probeer het opnieuw</a></p>
{% endblock %}

electionapp/voting/templates/thanks.html
{% extends "base.html" %}

{% block title %}
Bedankt
{% endblock %}

{% block contents %}

<a class="btn btn-primary" href="{{ url_for('index') }}">Terug naar Home</a>
<a class="btn btn-primary" href="{{ url_for('admin.login') }}">Log in</a>

{% endblock %}

electionapp/voting/templates/vote.html
{% extends "base.html" %}

{% block title %}
Stemformulier
{% endblock %}

{% block contents %}
<h1>Welkom bij de Waterschapsverkiezingen</h1>
<form method="post" action="{{ url_for('voting.vote') }}">
    {{ form.hidden_tag() }}
    <div class="mb-3 formgroup">
        <div class="formlabel">{{ form.name.label }}</div>
        <div class="forminput">{{ form.name }}</div>
    </div>
    <div class="mb-3 formgroup">
        <div class="formlabel">{{ form.party.label }}</div>
        <div class="forminput">{{ form.party }}</div>
    </div>
    <div class="mb-3 formgroup">
        <input type="submit" class="btn btn-primary" value="Stem">
    </div>
</form>
{% endblock %}